player = undefined
# 5. The API calls this function when the player's state changes.
#    The function indicates that when playing a video (state=1),
#    the player should play for six seconds and then stop.
done = false

onPlayerReady = (event) ->
  event.target.playVideo()
  return

onPlayerStateChange = (event) ->
  if event.data is YT.PlayerState.PLAYING and !done
    setTimeout stopVideo, 6000
    done = true
  return

stopVideo = ->
  player.stopVideo()
  return

window.onYouTubeIframeAPIReady = ->
  console.log 'CALL'
  player = new YT.Player 'player',
    height: '390'
    width: '640'
    videoId: 'M7lc1UVf-VE'
    events:
      'onReady': onPlayerReady
      'onStateChange': onPlayerStateChange
  return

# 4. The API will call this function when the video player is ready.


# ---
# generated by js2coffee 2.0.4